# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Pushes to Firebase App Distribution"
  lane :beta do
    build_ios_app(
      output_directory: "build",
      output_name: "rainbowSnake.ipa",
      export_options: {
        method: "development"
      }
    )
    firebase_app_distribution(
      app: ENV.fetch("FIREBASE_APP_ID"),
      testers: "theo.carrive@gmail.com",
      release_notes: "Hello you!",
    )
  end

  lane :release do
    sync_code_signing(type: "appstore")
    build_app(scheme: "RainbowSnake")
    upload_to_app_store
  end

end